### ISSUE TITLE
layout problem on small screen

### ISSUE THREAD

**Issue by mikelmaron** [jenningsanderson/data-team-edits#2]
buttons squashed on 11 in mac screen

![screen shot 2018-09-10 at 9 47 49 am](https://user-images.githubusercontent.com/22896/45302197-a775f680-b4e0-11e8-953f-126919e70fa2.png)

**Comment by jenningsanderson** [comment]
Fixed by making timeline a bit smaller and adding overflow scrolling to description; should work on displays down to 1366px wide now.
