### ISSUE TITLE
time box time user is on data team

### ISSUE THREAD

**Issue by mikelmaron** [jenningsanderson/data-team-edits#3]
how hard would it be to time box when someone was on a data team?

for example, would be great to capture AYC folks, before they went to DevSeed in Dec 2017.

**Comment by jenningsanderson** [comment]
- [x] active Since
- [x] active Until
- [x] users switching between teams. 

Data files are here [CSV](https://github.com/jenningsanderson/data-team-edits/tree/master/teams)
